#########################
# 🌐 Server Settings
#########################
server.port=8080
#########################
# 🔤 Encoding (UTF-8)
#########################
server.servlet.encoding.charset=utf-8
server.servlet.encoding.force=true
#########################
# 🛠️ Application Info
#########################
# 콘솔 ANSI 색상 출력 (VSC 콘솔 하이라이트용)
spring.output.ansi.enabled=always
#########################
# 🗄️ Database (H2 In-Memory)
#########################
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test;MODE=MySQL;
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
#########################
# 🧬 JPA / Hibernate
#########################
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#########################
# 🧪 테스트용 더미 데이터
#########################
spring.sql.init.data-locations=classpath:db/*-data.sql
spring.jpa.defer-datasource-initialization=true
#########################
# 📜 Logging
#########################
logging.level.com.metacoding.laviu=DEBUG
logging.level.org.hibernate.userTypeEnum=TRACE
#########################
# 🔥 Firebase Admin SDK
#########################
#########################
# ☁️ Sentry Io
#########################
# Sentry SDK가 에러 리포트를 전송할 프로젝트의 고유 주소입니다.
# 이 값이 없거나 틀리면 에러가 Sentry로 전송되지 않으니 정확하게 입력해야 합니다.
sentry.dsn=
# (선택 사항) 디버깅 시 유용한 설정
# Sentry SDK의 내부 동작 로그를 보고 싶을 때 true로 설정합니다.
# 연동이 잘 안될 때 "Sentry DSN is null or empty. Sentry is disabled." 같은 로그를 확인할 수 있어 유용합니다.
sentry.debug=true
# (선택 사항) 애플리케이션의 어떤 환경에서 에러가 발생했는지 구분하고 싶을 때 사용합니다.
# 예: local, development, production
sentry.environment=development
# (선택 사항) 어떤 버전의 코드에서 에러가 발생했는지 추적하기 위한 버전 번호입니다.
# build.gradle에 설정된 버전과 맞춰주는 것이 좋습니다.
sentry.release=laviu@0.0.1-SNAPSHOT
# mustache request expose
spring.mustache.servlet.expose-request-attributes=true
spring.mustache.servlet.expose-session-attributes=true